brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
edition = "2021"
empty_item_single_line = false
group_imports = "Preserve"             # `StdExternalCrate` once groups can be specified
imports_granularity = "Crate"
max_width = 120
newline_style = "Unix"
trailing_comma = "Vertical"
