name: ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Cache Rust files
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - run: cargo fmt --all -- --check
          
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Cache Rust files
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - run: cargo clippy --tests -- -D warnings

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache Rust files
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - run: cargo test --verbose